#!/bin/bash

export WINEPREFIX="$HOME"/.playkey-linux/wine_prefix

if [ ! -d "$HOME"/.playkey-linux ] ; then
	echo "Creating playkey-linux folder "$HOME"/.playkey-linux"
	mkdir -p "$HOME"/.playkey-linux || exit 1
	mkdir -p "$HOME/.playkey-linux/wine_prefix/drive_c/Program Files (x86)/" || exit 1
	cp /usr/share/playkey-linux/xdg-open "$HOME"/.playkey-linux || exit 1
	ln -s /usr/shar/playkey-linux/ "$HOME/.playkey-linux/wine_prefix/drive_c/Program Files (x86)/" || exit 1
fi

PATH="$HOME/.playkey-linux":$PATH
echo $PATH
chromium "https://playkey.net"
# wine "$HOME"/.playkey-linux/playkey.exe
